---
- name: 1. Setup VM Host (Install KVM/Libvirt)
  collections:
    - ansible.posix
    - community.general
  hosts: vm_host
  become: yes
  roles:
    - vm_host_setup_only
    
- name: 2. Build repo VM
  collections:
    - community.general
  hosts: vm_host
  become: yes
  tasks:
    - name: Call vm_builder role for repo
      ansible.builtin.include_role:
        name: vm_builder
      vars:
        vm_name: repo
        vm_ip: "{{ hostvars['repo']['ansible_host'] }}"
        vm_os_variant: centos-stream9
        vm_kickstart_template_name: repo_kickstart.ks.j2
        vm_location_url: "http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/"
        vm_ram: 8192 # 8 GB RAM
        vm_disks:
          - path: /vmfs/rhcsa_storage/repo_1.qcow2
            size: 30

- name: 3. Configure and Mirror Content on repo VM
  collections:
    - ansible.posix
    - community.general
  hosts: repo
  gather_facts: no
  become: yes
  roles:
    - repository_server_setup
  
- name: 4. Build Exam VMs (VM1 and VM2)
  collections:
    - community.general
  hosts: vm_host
  become: yes
  tasks:
    - name: Build VM1 (Exam VM 1 - Multi-Disk Setup)
      ansible.builtin.include_role:
        name: vm_builder
      vars:
        vm_name: vm1
        vm_ip: "{{ hostvars['vm1']['ansible_host'] }}"
        vm_os_variant: centos-stream9
        vm_kickstart_template_name: vm_kickstart.ks.j2
        vm_location_url: "http://{{ hostvars['repo']['ansible_host'] }}/centos9stream/BaseOS"
        vm_ram: 8192 # 8 GB RAM
        vm_disks:
          - path: /vmfs/rhcsa_storage/vm1_root.qcow2
            size: 10
          - path: /vmfs/rhcsa_storage/vm1_db.qcow2
            size: 5
          - path: /vmfs/rhcsa_storage/vm1_swap.qcow2
            size: 1
            
    - name: Build VM2 (Exam VM 2 - Break Scenario)
      ansible.builtin.include_role:
        name: vm_builder
      vars:
        vm_name: vm2
        vm_ip: "{{ hostvars['vm2']['ansible_host'] }}"
        vm_os_variant: centos-stream9
        vm_kickstart_template_name: vm_kickstart.ks.j2
        vm_location_url: "http://{{ hostvars['repo']['ansible_host'] }}/centos9stream/BaseOS"
        vm_ram: 8192 # 8 GB RAM
        vm_disks:
          - path: /vmfs/rhcsa_storage/vm2_root.qcow2
            size: 15

- name: 5. Final Configuration and RHCSA Objectives Setup on Exam VMs
  collections:
    - ansible.posix
    - community.general
  hosts: rhcsa_vms
  become: yes
  roles:
    - vm_configuration